name = "dados-ooh-worker"
main = "src/index.js"
compatibility_date = "2025-12-16"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "dados-ooh-worker-prod"

[build]
command = "npm install"
