name = "dados-ooh"
main = "worker.js"
type = "javascript"
compatibility_date = "2025-12-16"
compatibility_flags = ["nodejs_compat"]

# Para Cloudflare Pages servir arquivos est√°ticos
[site]
bucket = "./public"

# Workers para API
[routes]
pattern = "*/api/*"
zone_name = "seu-dominio.com"

[env.production]
name = "dados-ooh-prod"

