name = "dados-ooh-worker"
main = "src/index.js"
compatibility_date = "2025-12-16"
compatibility_flags = ["nodejs_compat"]
account_id = "458e6d616cddf6660731e71235fe4c45"

[env.production]
name = "dados-ooh-worker-prod"

# Vari√°veis de ambiente
[env.development]
vars = { GOOGLE_SHEET_NAME = "Sheet1" }

[[env.development.r2_buckets]]

[[env.development.d1_databases]]